### ISSUE TITLE
A post-release refactoring in the Global Configuration

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#100]
I think that we can agree that the quantity of labeled controls  in the Configuration options is too dense and the response latency from having it interactive with the view will be a problem.

I was looking at the Global tab an thought of a possibility for making it tighter and more intuitive.  Here is how it exists now:
![image](https://user-images.githubusercontent.com/69127217/145277380-0aacdb78-1d4a-4540-a141-5828ba57a6ac.png)

But a LARGE number of the switches could be compactly controlled with a psuedo family section and with a small toolbar. Let's say you have a toolbar with a "±" button and a Configure button.  The person above would have the "enabled" elements as they would appear for a record in the GUI. The panel below has 2 (or 3 states). 
![image](https://user-images.githubusercontent.com/69127217/145277939-707dbf04-09b1-4f9e-9b8b-fbd40b3f25ea.png)

With the ± toolbar control active, the lower panel is similar to top but has the palette of "disabled" elements and as much as possible is 'dimmed' to indicate it is inactive content. Clicking on an element (in either the Enabled or Disabled panel) moves it to the opposite panel. 

With Configure tool active, the contents change dynamically to have detailed options for the selected element.  There might be marquees overlaid in the top panel for clickable areas. Clicking these would reveal options for that section. For instance there might be a box around the Secondary Object icons where you could change the sort order of Tags (Priority/Alphabetical). And another option to show a summary count before the icon of each type (3 names, 2 parents, 16 sources, etc.), or a choice between 16x16 & 22x22 secondary icons.  And perhaps a series of color swatches (either single color swatches or dual color foreground/background swatches) on the toolbar with callout lines pointing to which object is controlled. 

In version 3.0, a possible 3rd state of the bottom panel might be an impressive Text description of the settings... reminiscent of a [blazon of arms](http://heraldry.sca.org/armory/bruce.html): "Argent on a bend Gules between two pellets, three fleurs de lis also Argent"

**Comment by cdhorn** [comment]
> With the ± toolbar control active, the lower panel is similar to top but has the palette of "disabled" elements and as much as possible is 'dimmed' to indicate it is inactive content. Clicking on an element (in either the Enabled or Disabled panel) moves it to the opposite panel.

That is an interesting thought but not something I'd spend my time on.

> option to show a summary count before the icon of each type (3 names, 2 parents, 16 sources, etc.)

Yeah I meant to add counts to the tooltips for those, but I can add an option to display the number as well probably.

Going to look closer at the config stuff itself over the next few days.

**Comment by cdhorn** [comment]
Indicator counts option just added in fd2b06d755ec721345b3655b822aa7d7a258e809

Simple config menu was added BTW, not sure where that is heading yet. Middle mouse click to activate.

**Comment by emyoulation** [comment]
> Indicator counts option just added in fd2b06d

Please revise the count method of Parents.  It is counting sets, not unique individuals. So a person with 2 sets of parents, which includes a set with a pair birth and a set with one of the original birth parents plus a step parent, would be 3 parents.  

Alternately if the count method remains unchanged, the hints should read that the count is "sets of parents" rather than "parents"

**Comment by cdhorn** [comment]
Good catch! Thought didn't enter my mind and it should have.

**Comment by cdhorn** [comment]
I am going to close this now as well in light of #93 and my comments there regaring the new configuration context menu. I don't forsee myself making any major changes in how the options are being handled now that is available.
