### ISSUE TITLE
Calculated user defined field types

### ISSUE THREAD

**Issue by cdhorn** [cdhorn/LinkedView#101]
Add a new user definable field type called Calculated and a set of special type definitions will be supported.

For Person: Lifespan, Living, Duration (both Lifespan and Living combined), Child Number, Paternal Progenitor, Maternal Progenitor
For Family: Duration, Relation

**Comment by emyoulation** [comment]
Will you have a calculation for Person age at Event/Media object date?

**Comment by cdhorn** [comment]
I think you mean using the age area like when you include Name, Media etc in the Person Timeline.  That is separate from this, but yes I intend to.

**Comment by cdhorn** [comment]
Refactor of user customizable field handling completed in f49625524c3eada0cc2f1173f36eda57fb75185d

Calculated field selections mentioned above implemented as well as an Occupations one that parses all the events and attributes of a person and builds a list of unique occupation names for display.

This was a good exercise, cleaned things up a bit. New fields are trivial to add now.
