### ISSUE TITLE
The bug in the "reset all" of the config is making testing harder

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#104]
I try to reset the Configuration every time a new beta is downloaded. Otherwise, it is impossible to determine if any problem is self-induced from obsolete settings. 

But whenever the "Reset all options to defaults, not just this page" option is used, the following "Unexpected error" pops:

```
28806296: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView\view\common\common_utils.py", line 408, in reset_option_space
    default_value = self.config.get_default(option)
  File "C:\Program Files\GrampsAIO64-5.1.4\gramps\gen\utils\configmanager.py", line 429, in get_default
    (section, setting))
AttributeError: No such config setting name: 'options.colors.roles.border-other'
```

The "`options.colors.roles.border-other`" recently was tweaked to allow "Unknown" roles to be unique.  Does something need to be done there?

I was thinking that the reset all would simple purge the .ini files related to the LinkedView (not only the myriad checkboxes but also the window positions of the sidebar/bottombar/main view and gramplet selections.  Then trigger a navigation into the view again.  (That probably means prophylactically dismissing any spawned windows from the LinkedView main/splitbars too!) I think that the sheer number of options in this View mean that backward compatibility may be an unrealistic hope.  The view will need an aggressive purge. 

(Other Views and gramplets also would have benefited from a more aggressive Configuration purge. Unfortunately, this is a heretical concept.)

**Comment by cdhorn** [comment]
See if a03ce9e5772ea6912416614f57151c00179d9294 helps. Doesn't cleanup old options but shouldn't fail when it stumbles over an old one.

**Comment by emyoulation** [comment]
Wonderful!  That fixed it!

**Comment by cdhorn** [comment]
Excellent! Closing this now.
