### ISSUE TITLE
Status icon indicators

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#106]
This is a "can I do something like this" not a feature request.

I currently include a sourcing attribution in the Description of my "Burial" Events because they are too transparent in the Events view & tabs otherwise.  (e.g., burials that have been located on FindAGrave  have " : FindAGrave xxxxxx" appended in the descriptions)

I think is more proper to use a Citation but they require too much drill down. (e.g., for People that have been found on FamilySearch, I have a "FamilySearch" Source citation with the profile ID as the Citation page plus a Confidence and page visit date.)

So, I intend to migrate the Burial descriptions to a Burial citations using Kari's SuperTool.
You're already planning/doing a kind of LDS's ordinances checklisting function for the LinkedView. Will it be adaptable to evaluating stuff other than ordinances?

Where there is a prominent sanity (might be the wrong word for anything related to a religious belief) checklist.  The LDS has a simple set of four to six 1|2 letter acronym with a background color for status.   
![image](https://user-images.githubusercontent.com/69127217/145561434-02df5593-4db5-4799-b463-c3ca5b6892b9.png)

So might this be adaptable to checklisting things a Person? Perhaps with a definable 2unicode character label instead of a preset indicating the status of a particular sanity check:
1) Does the primary object have a specific source cited (such as the primary Lineage Book on your family or an online source like FamilySearch, WikiTree or Ancestry) and what is the confidence as the status color?
2) Is there a particular type of 2ndry object (a specific type of Event with a status color-coded by existence of a tag, attribute, date, exact date, Place, specific source) e.g., a Burial event with a FindAGrave citation is green, no citation is grey.

**Comment by cdhorn** [comment]
> You're already planning/doing a kind of LDS's ordinances checklisting function for the LinkedView. Will it be adaptable to evaluating stuff other than ordinances?

What I had in mind was to add a coloring scheme for ordinance frames based on the status code. The ordinance frame itself already displays the status. Not hard, just not a priorty. But then maybe I misunderstood the suggestion, have to go back and look as already forgot it. 

> So might this be adaptable to checklisting things a Person?

I see what you are asking. Almost anything is possible given time.

To do something like this you need to derive some generic mechanism for the user to define the rule and then something to parse and evaluate the data against the rule to produce the result to be rendered.

You can think of the coloring schemes as working that way, just the rule/business logic is implemented in code.

It would be a handy feature for power users. This sort of indicator could be put with the other icons, or maybe on or beneath the Gramps id section.

**Comment by cdhorn** [comment]
@emyoulation I have thought about it and am not going to implement something as fancy as described above. But I have started an implementation for a set of standard status indicators I think will be useful. The planned ones are below, let me know if you think of any others similar to these that might be useful.

**Confidence ranking indicator**

For people only. This will be calculated based on the highest confidence scores of citations found on a particular list of key user selectable events. A set of star icons will be used to indicate overall status based on the score and the score exposed in the tooltip. The idea here is to provide some indication of how well researched an individual is.

**Citation alert indicator**

For people only. This will have the minimum confidence level required to be met on a particular list of key user selectable events. If one of those events is found and a citation is missing on one of those events or the highest confidence found falls below the minimum the indicator will be shown and the tooltip will have a list of which ones failed the test and why.

**Missing event indicator**

For people only. If an event is missing the citation alert indicator will not reflect that, so this will examine a list of required events and if any are missing will trigger and the tooltip will have the list of missing ones.

**To do indicator**

For objects with notes. This will trigger if a to do note is found for the object or any of it's children. For people and families I will likely add an option to also examine if a do note is present on any of their referenced events as well.

**Comment by cdhorn** [comment]
Initial iteration for this committed now, .072.  The attribute indicator is unimplemented, it opens a can of worms as we have different custom attributes on different objects.

Note the todo and citation alert icons have popup menus with list of items found.

**Comment by cdhorn** [comment]
I am closing this out now since the initial iteration is in place.
