### ISSUE TITLE
Future feature: Print the view?

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#108]
Some Chart view modes (Fan charts) and all the Geography view modes have a Printer toolbar option. And a few Chart view modes (Life Lines add-on) have Save toolbar features. 

Do either of these make sense for the LinkedView?

**Comment by cdhorn** [comment]
Hope you don't mind but going to close this one.  It is an interesting idea I had not considered but not something I intend on spending any time on.

**Comment by cdhorn** [comment]
It or something similar might be useful if any other developers want to lend a hand.  The problem for me is one of time, there are some other things I want to try to do that for me would provide more value. I am also not sure if the internal design lends itself well to that.
