### ISSUE TITLE
Standard Gramps terminology: "Home person" not 'default'

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#109]
In the context menus for People, where the menu item is: a People category icon & "Make the default person", please change to: a home icon & the previously weblated menu phrase: "Set Home Person"

**Rationale:**
The 'default' being used to refer to the Home Person setting is a legacy from the original coding we are trying to purge. (See [MantisBT bug 11078](https://gramps-project.org/bugs/view.php?id=11078) )

Wherever possible, change ambiguous uses of 'default' that refer to the Home Person (Rather than 'default' instances that identify a generic default value for a setting/variable.)

**Comment by cdhorn** [comment]
Agree I will take care of this.

**Comment by cdhorn** [comment]
If you see other inconsistencies like this please open issues. The date rendering I just now realized and opened.

**Comment by cdhorn** [comment]
This should be fixed now.
