### ISSUE TITLE
Toolbar labels are non-standard

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#113]
When "Toolbar text" is enabled via the Themes (preferences) add-on, the icon labels are overly verbose & non-standard. The long labels cause too much spread in the Toolbar.

Each object type has different toolbar icons but all need to be tightened up.
In the Person page of LinkedView mode:
Your toolbar label : standard label

_Add New Parents : Add
_Add Existing Parents : Share
_Add New Spouse : Partner
Linked View Help (no translation indicator?) : Help

--------
(The following label & hint has probably changed if you've harmonized instances of 'default person' to 'home person' but the question remains valid.) I do not understand the "Set Active" (tooltip: "Make active person the default") functionality... nor using the "Person" icon unconventionally. 
Wouldn't it be more intuitive to use the Home toolbar icon? Left-click to navigate, right-click to set?

**Comment by cdhorn** [comment]
Partially fixed, actually I broke the Add/Share/Partner actions themselves with the page copy refactor and didn't realize it. Don't see my mistake at the moment.

**Comment by cdhorn** [comment]
Oddly the toolbar items for Family work, but for Person and Event do not. I see no reason one would and the others not and am really baffled.  I am hoping when Nick or Paul are able to do a code review perhaps they will spot the issue.

**Comment by cdhorn** [comment]
Closing this one as should be fixed as well now. 

Note bookmarks should be working now as well. ie. when primary object is source you get source bookmarks on drop down, family then family bookmarks, etc.  Previously it was pinned to person bookmarks.

Easter egg ctrl-right click for bookmark navigation context menu.

**Comment by emyoulation** [comment]
Would you consider changing the Copy Panel toolbar label from "Copy" to something like "Clone"? 

The "Copy" label has some implicit "clipboard" connotation.

This powerful feature is too easily overlooked to allow the label to be ambiguous.
