### ISSUE TITLE
Places breadcrumbs

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#114]
Would it be a big deal to change the display when a Place is the focal object?

Right now, if a populated place is under several hierarchical layers of civil divisions, it is fairly hard to access the enclosing divisions.

As an example, let's take a populated place of Eastbrook. It is in the township of Hickory within the county of Lawrence in the commonwealth of Pennsylvania and part of the nation of USA.

The Place LinkedView panel has a single object: "Eastbrook, Hickory, Lawrence, Pennsylvania, USA".

It would create more access to have 5 clickable/draggable breadcrumb objects separated by commas: "Eastbrook", "Hickory", "Lawrence", "Pennsylvania", "USA". And to have rollover hints identifying the Type.

The other thing to note is that the Place panel lists all the direct references to that place.  But it ignores the references by enclosed places. So if I had Hickory township as my selected place, it would not list Events in Eastbrook, nor Burial Events in the Covenanter Cemetery in Eastbrook. An "Enclosed" option would be a possible FUTURE (post-release) improvement.

**Comment by cdhorn** [comment]
Both good ideas, on the to do list.

**Comment by cdhorn** [comment]
Closing this as this is pretty much done now.

Breadcrumb links with tooltips implemented when place is the focal object in the header. Not going to add when in a group because of word wrap funkiness.

I added an Enclosed Places group and there is a recursion option to pull in all the subordinate places. And I added the place timeline which also recursively iterates looking for events.  Because you can get thousands of them I set reasonable limits and there is a Group Limits tab under the Global configuration panel now.

Context menu has support for adding new or existing enclosed places. Reference can be edited or deleted via context menu as well.

**Comment by emyoulation** [comment]
Id: linked_view (Windows 10)
Description: A browseable object view.
Version: 0.71

The breadcrumbs as Hyperlinks turned out to be not as useful as I hoped.  It is OK for navigation but you don't get the extra functions. Since the context menus key off the panels rather than links, you cannot edit the enclosing placed or add them to the clipboard without navigating to them 1st.  
Perhaps another stacked Places section for **Enclosing Places** to augment the one for **Enclosed Places**? If that gives the extra functionality, might as well strip out the code that breaks the Place string into breadcrumbs.

![image](https://user-images.githubusercontent.com/69127217/147006388-d8465e5b-1eae-416e-a277-a554d72b757c.png)

**Comment by cdhorn** [comment]
Yes, I could do that by adding another group and the thought had occurred to me when I was adding the enclosed ones.

The other thought is in the header to have the top level place first and then each place beneath till get to the one in focus. Thoughts?

**Comment by emyoulation** [comment]
Unless you find a way to make the Place Placards much more compact, putting the Enclosing places as a cascade in the header could leave very little vertical space for the 2ndry sections. Some of my places have 5 or 6 levels in the hierarchy. The header option seems less viable than another collapsible section.

Have you thought about compositing lat/long so that coordinates only eat 1 line?

**Comment by cdhorn** [comment]
I see you're point about using the header for that, and yes we could collapse lat/lon.  I'll revisit this when I'm done with the status stuff.

**Comment by emyoulation** [comment]
Cool.  If you use a composite lat/long, make sure you leave something searchable for the formatting.  Hopefully, a user preference will be added for the [Supported longitude/latitude formats ](https://gramps-project.org/wiki/index.php/Gramps_5.1_Wiki_Manual_-_Entering_and_editing_data:_detailed_-_part_2#Supported_longitude.2Flatitude_formats) similarly to how you can choose a Date or Name format. (The Places View is currently locked to "degree, minutes, seconds notation".)

**Comment by cdhorn** [comment]
Shouldn't matter much, if a lat/lon displayer was added to complement the name/date/place ones it would be a simple change to use it.

**Comment by cdhorn** [comment]
Enclosing places group added 33ee7ca81b07c903ab9246621a778ecd1d31c38d and lat/long on single line in ef0247060ce1d3a8065792935c21ad030fd64b91 so reclosing this now.

**Comment by cdhorn** [comment]
> If GPS display format control is added (see Feature Request 11248), you'll have to go back and support it later.

Should probably have an address displayer as well that outputs the formatted address as a list of lines. I'm not familiar with international addressing but I'm sure they all vary a bit from how we address stuff internally in the US.
