### ISSUE TITLE
Minimize of Copy Page affect application, not just spawned window

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#116]
Thanks for including a Minimize gadget on the Copy Page (cheatsheet? Crib note? Scratch pad?) and other spawned windows. 

(No other dialogs in Gramps can be minimized. So those can sometimes be a real challenge for single-screen users to expose enough screen real estate to do drag'n'drops. Particularly when the dialogs are third-spawn from different objects and the drag'n'drop hotspot are small spots in the middle of big dialogs. i.e., {before LinkedView was available} dragging the cemetery Place from the burial of one Spouse to the Burial of the other. From spawned Edit Relationship, open each spouse and the burial event in each spouse. 5 spawned dialogs! The only reasonable method is to stage the data into the clipboard. The spawn count drops to only 4.)

I had hoped to expose the clipboard by minimizing the Copy Page. But the whole app (except the original CLI window) minimized!

**Comment by cdhorn** [comment]
AFAIK minimize is a window manager function, not something built into Gramps. The behaviour you describe I think is Windows specific as with Fedora it seems to work fine and I can minimize any window I want individually separate of the others. So this isn't something I can do much about.

**Comment by emyoulation** [comment]
I just did a test with GIMP, where the GTK toolkit originated.  When multiple image files are open, each in their own window, they can be minimized individually. (When the last non-minimized window is minimized, the reset of the Application windows minimize with it.)

[Requested Developer feedback](https://gramps.discourse.group/t/gtk-and-limiting-the-minimize-gadget/2469) on the Discourse forum.

It might be easier to just remove the Minimize gadget from the pinned Windows?

**Comment by cdhorn** [comment]
Yeah I wonder/think this has something to do with that WinAIO thing or whatever that is used to package the Windows version.
