### ISSUE TITLE
Add Preferences button to Color config tab

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#117]
The [Isotammi Config](https://github.com/Taapeli/isotammi-addons/tree/master/source%2FIsotammiConfig)  Gramplet for the dashboard view has a button to open the Gramps core Preferences.

Instead of having a header in each of the LinkedView Configuration pages for the Color tab, perhaps LinkedView Configurations could have a similar button that opens the Colors tab in that feature? (Switching to a specific tab might not be an option.)

And perhaps the order of the 2 header lines could be swapped?  The "See global preferences for option to switch between light and dark schemes" requires an add-on -- which may not exist on all installations. So that item should be 2nd. You could link it to `https://www.gramps-project.org/wiki/index.php/Addon:Themes` to eliminate the documentation burden.

Chances are that 5.2 or 6.0 will roll the features in the Themes into the core.  (This would require redistributing the add-on:Theme options. So the core "Colors" Preferences tab may be renamed. Hopefully, the new 5.2 will be "newbie oriented" with original built-in Navigator sidebar labels & the themes Toolbar labels enabled by default. Especially since the navigator sidebar label option requires restarting Gramps.) Gramps could take advantage of the ability to detect the OS's light/dark preferences and adapt the theme switch & color schemes automagically.

https://stackoverflow.com/questions/50840168/how-to-detect-if-the-os-is-in-dark-mode-in-browsers

**Comment by cdhorn** [comment]
> Instead of having a header in each of the LinkedView Configuration pages for the Color tab, perhaps LinkedView Configurations could have a similar button that opens the Colors tab in that feature?

Sorry I guess I'm not following you at all here, there is only the 1 Colors tab in the base configuration Notebook. The vertical options were implemented for each tab by then embedding a Notebook and using the side tab option instead of having them horizontally beneath the first set of tabs which I thought might lead to more confusion.

**Comment by cdhorn** [comment]
I did just revisit the color preferences though and unrolled it so both light and dark schemes are presented together.

**Comment by emyoulation** [comment]
![___Conf.png](https://user-images.githubusercontent.com/69127217/146624200-15da8e02-8c92-4958-a1ef-fcf28c8eaf11.png)

This was not immediately when you  stick with the default Light themes variants (which I do). Since so many users mention dark theme, after selecting Dark theme, you immediately discover that the broad stroke colors visible in the Person Linked View are the Gender panels & default panels. Those Colors are set in the Global Preferences. 

So the dialog will be well served with a prominent shortcut to where those colors can be set. The header of the Colors tab (where it talks about using the Global Preferences) is the obvious place for the shortcut/button.

![___Pref.png](https://user-images.githubusercontent.com/69127217/146624204-eed231e9-11f2-496f-9242-22397aeeeb19.png)

**Comment by cdhorn** [comment]
Added Preferences button to the color scheme config panels in 81ea347bfa9f43e302572f020ac916369be0ce43 so going to close this now.
