### ISSUE TITLE
Drag (rollover) Children Panel error

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#120]
Linked []Gramps View] Version: 0.75

Dragging a person overtop of the blank portion of a Children (or siblings) panel generates an error. (Not dropping there, merely dragging over it.)

Open the example Tree
copy a few people from the People View to the clipboard
switch to the LinkedView
find a person with few sibs or children. (I used Melissa Sue Garner I01041)
   In the Parents and Siblings stack, there is a white/blank area below the Siblings panel
   In the Spouses and Children stack, there is a white/blank area below the Children panel

Drag a person from the Clipboard over either of the white/blank areas 

The following error occurs:
 
8491909: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView\view\groups\group_list.py", line 165, in on_drag_motion
    allocation = current_row.get_allocation()
AttributeError: 'NoneType' object has no attribute 'get_allocation'

**Comment by emyoulation** [comment]
I had been hoping to be able to add a Child or Sibling by dropping a Person onto the blank area

**Comment by cdhorn** [comment]
Yes that ought to work and it does on my system.  I might have fixed that the other week though and not bumped the version or pushed it upstream though.

Regarding missing spouse drop support I added that not that long ago if I recall. Using the _____ as a visual queue for the compact family frame to indicate a missing spouse and that you can drop there is not a bad idea. 

Large design change made this weekend, still sorting things out before I push it upstream. A lot of work but cleaned up a lot of things. It was what I was trying to get my head around about a month ago but couldn't fully see at the time.

**Comment by cdhorn** [comment]
Please check latest when you have a chance and let me know if child drop still causing issues.

**Comment by emyoulation** [comment]
The problem still exists in the 0.77 version. The error is not on the drop. Just on the rollover while dragging a Person object. It seems to be when the panel is trying to decide what to highlight but there is no panel in the stack to index where one is expected.

2022-01-03 23:02:26.730: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView\view\groups\group_list.py", line 165, in on_drag_motion
    allocation = current_row.get_allocation()
AttributeError: 'NoneType' object has no attribute 'get_allocation'

![image](https://user-images.githubusercontent.com/69127217/148012609-4a221b26-2b7b-4211-b6c7-3b658c39f097.png)

**Comment by cdhorn** [comment]
Oh yes I see, duh. Added a test for that and just pushed the fix. Should take care of it.

**Comment by emyoulation** [comment]
Great! Works now.
Wanna grep a mass Copyright update to 2022 ?

**Comment by cdhorn** [comment]
Ah good!  Closing this now.

That would be sed not grep!
