### ISSUE TITLE
Browse view does not initialize 

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#121]
Plugin name: Linked [Gramps View] 
Version: 0.75

deselect the "Remember last view displayed" option in the Preferences General tab
deselect the "Automatically load last Family Tree" option in the Preferences Family Tree tab
In the Example.gramps tree
set the active person to Melissa Sue Garner... (who is NOT the home person)
bookmark her

quit Gramps
start Gramps 
choose the example.gramps tree 
default view is the Dashboard
switch to the Browse view
    **view is blank** -- except the Status lists the Active Person (from my previous session, this was Melissa Sue Garner)
click the Home toolbar button
  **The status bar does not change, the Active Person remains Melissa Sue Garner, there is no refresh**
  _The Home toolbar button not working is a secondary bug._
Change the Active Person focus (using Bookmarks to re-select Melissa Sue Garner)

The Browse view is now populated

(Changing the Active Person via the Person View also initializes the Browse view)

The only time the view populated properly upon Gramps start was if it was the initially Active view via a "Remember last view displayed"

**Comment by cdhorn** [comment]
Acknowledged, yes I've seen this since I last touched the nav related code and need to sort it out.

**Comment by emyoulation** [comment]
Please also check what happens when initializing the view with:
* tree with no records
* no Active Person
* no Home Person
* No database loaded (See error below:)

433901: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.1.4\gramps\plugins\sidebar\dropdownsidebar.py", line 119, in __category_clicked
    self.viewmanager.goto_page(cat_num, None)
  File "C:\Program Files\GrampsAIO64-5.1.4\gramps\gui\viewmanager.py", line 786, in goto_page
    self.__create_page(page_def[0], page_def[1])
  File "C:\Program Files\GrampsAIO64-5.1.4\gramps\gui\viewmanager.py", line 840, in __create_page
    self.active_page.post_create()
AttributeError: 'NoneType' object has no attribute 'post_create'

**Comment by cdhorn** [comment]
The unhandled exception would seem to be a bug in Gramps core. Furthermore I see the post_create method in the 5.1 branch but it does not appear in the master aka 5.2 branch.

**Comment by cdhorn** [comment]
Many of these scenarios I think are sorted now.

**Comment by cdhorn** [comment]
Fairly sure these scenarios where sorted out so closing this now.

**Comment by emyoulation** [comment]
The primary bug is now resolved.  The Browse view handled the 4 problematic scenarios (no tree, no people, no active person, no home person)

The problem still exists where the Browse view's Home toolbar button doesn't cause a refresh on a freshly instance of Gramps after loading a Tree saved where Active Person is not the Home Person. You have to change the Active Person to someone else before the Home Button does anything.
