### ISSUE TITLE
Delete from a linked view should delete the Link, not the object

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#122]
Gramps is pretty consistent that the only GUI location from which you can delete (or Merge) objects is from the corresponding category View.  (Although Creation/Add can be done from anywhere.) This is because objects can shared secondary objects to a multitude of primary objects.

Deleting in other places disconnects secondary object from its primary objects instead.

Unless a dialog appears warning of all the References that will be broken and a Merging option can be be integrated, please eliminate deleting of Objects from the Contextual menus for LinkedViews.  Contextual Options to delete/remove and individual Secondary-to-Primary reference are OK, but not the object.  

Example, right-click a Sibling (who has a spouse) in the Parents and Siblings stack. 
The context menu includes:
* <kbd>-</kbd> Delete Person
* <kbd>-</kbd> Remove Child from this family

Yet the context menus for other views ofter to delete the object without the option to unlink it.
Click a Note to change the focus, right-click a panel in the Reference stack:
* <kbd>-</kbd> Delete Event
There is no option to unlink the Note from the Event

The **Remove <code>&lt;secondary object></code> from this <code>&lt;primary object></code>**  is more link the "Clear Markup" button in the Note Editor.  Perhaps these menu options should ust that toolbar icon rather than the <kbd>-</kbd> hyphen icon?
![image](https://user-images.githubusercontent.com/69127217/148817160-8dd6fb87-7d7d-4174-8514-7446f64b6c74.png)

If you wish to leave something as potentially destructive as the Delete <code>&lt;secondary ojbject></code> in the menu, it should be in the bottom-most position and should have a better warning than the current one:
![image](https://user-images.githubusercontent.com/69127217/148816145-0dab82ca-9cce-4078-abdc-2770394c4ab3.png)
or even the one currently built into the Gramps category view: 
![image](https://user-images.githubusercontent.com/69127217/148816368-863434e2-aed8-4adf-8151-7505b13d7de3.png)

It should have a warning of how many (and have a list) references exist for the Object.
   

Alternately, put the destructive meno option at the bottom-most position in the menu.

**Comment by cdhorn** [comment]
The delete functionality is using the same code David put together for the WebAPI and it should be deleting all the references as well. So that should be covered.

I considered making the addition of the delete options on the context menus, and maybe even some of the other menu options, user configurable. I will revisit that so you can enable or disable it, and perhap choose the current location or to append it at the bottom under the last change date.

I should track down and use the same warning and confirmation dialogs as Gramps to be consistent. So I will revisit that as well.

And I like the thought of providing a count of references that will be removed with the object.  So I will add that.

**Comment by emyoulation** [comment]
Didn't notice the markdown was hiding some of the content. Tweaked to make that visible

**Comment by cdhorn** [comment]
The delete option and many other context menu entries are now configurable as you may have already noticed.

I switched and am using the default Gramps question dialog now so the look/feel is consistent. I should have used that from the start.

I provide a count of back references in the delete dialog.  That is really not the proper place to list items like you propose, there could be a handful or there could be a few hundred.

![Screenshot from 2022-01-17 23-49-34](https://user-images.githubusercontent.com/43528418/149872938-125bd205-0f38-48ef-a8a7-9ca2faebb792.png)

Having a count should provide the user with a reasonable cue.  So with that I am going to close this out.
