### ISSUE TITLE
Parent and Spouse panels have strange extra white space

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#123]
The "Parents and Siblings" & "Spouses and Children" have 

![image](https://user-images.githubusercontent.com/69127217/148829055-e1b326d7-15d0-4643-b093-d799234f2301.png)

In the example above, the other stack have been minimized. (This is irrelevant.) But expanding the vertical height of the Gramps window dynamically adjusted the height of the Parents panel.  It seemed to be some multiplier of the siblings/children count. Where there were 13 sibs and 7 children, the parent/spouse panels were 4 screens high. (The overall height was 11 screens of scrolling.) But the sample above with only 2 sibs has the Parent panel being equivalent to the combined heights of both sib panels combined.

**Comment by cdhorn** [comment]
Yes I don't see this on Fedora at all.  I know at some point I need to spin up Windows VM again and spend some time with it there as some things apparently behave differently.

**Comment by cdhorn** [comment]
Confirmed this is a problem to be fixed.
