### ISSUE TITLE
Browse view toolbar icons for view modes?

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#129]
Part of reorienting oneself in the new Browse view is not only recognizing what object type is currently the active object, it is also recognizing when you have been in the view mode before & when there are view modes that you have not explored.

Could a set of View Mode toolbar icons be added, one for each mode?  The current view mode could be highlighted 

Since it is unconfirmed whether such an approach would be beneficial, perhaps a 1st mockup could use Unicode circled alphanumerics instead of waiting for distinctive icons? (Particularly since some of the view modes are for object types that are not categories.)

http://www.alanwood.net/unicode/enclosed_alphanumerics.html

⓮ | ⓯ | ⓰ | ⓱ | ⓲ | ⓳ | ⓴

**Comment by cdhorn** [comment]
> Could a set of View Mode toolbar icons be added, one for each mode? The current view mode could be highlighted

It is better to think of them as pages. Person page, Person Ref page, Family page, Tag page, etc...

I don't think displaying 19 icons in the tool bar and only having one highlighted, along with the existing icons, really makes much sense.

And clicking any of them wouldn't necessarily produce an action either.  I could search the nav history to see if the page was ever referenced/displayed for an object previously but not sure there is value in that.  You have the Go menu, albeit it only handles primary objects, and forward and backward of course which do handle the secondary objects.

I see your concern however.  I think it can be addressed with the status bar, I can display the page name in () after the description.  So I'll leave this open for that purpose when I am done with the second template iteration.

**Comment by cdhorn** [comment]
Added the page description to the status bar in 800a64fe48820d55f978f444320a72f186cf1b5f
