### ISSUE TITLE
Enable drag and drop to add a person to an event in event group or timeline

### ISSUE THREAD

**Issue by cdhorn** [cdhorn/LinkedView#23]

**Comment by emyoulation** [comment]
How would you handle Role selection? 

The default used be Gramps is to set the Roles to Unknown when sharing an Event. Not only is it bad that Gramps doesn't complain about a condition that it knows cannot EVER be valid (like Gramps complains about an unknown gender while saving a Person record), it is bad that Gramps cannot set a Preferred Role when creating added References (like the Preference setting for the default Relationship type for new Families.

I've thought in the past that some sort of data Painter/Eyedropper functionality might be utterly cool. In MSWord, Excel or Photoshop, I can pick up a formatting style or color and then paint word, cell, or pixels with it.

So it'd be great to pick-up a place (like the family homestead or cemetery) from one Event or the Clipboard and be able to paint the other children's Birth or Burials with that Place. WITHOUT opening the Event Editor.  Likewise, pickup a Census Event from the HeadOfHousehold, switch the Paintbrush from painting "Primary" Role to "Dependent" and then paint the the other Household members with that census Event. Or, pickup an Obituary citation and paint paint the Birth, Death, Burial events of the deceased, the the mentioned residences of the attendees.

**Comment by cdhorn** [comment]
Added in b7459b9f30cb6e962fe6e388ca0166e497620fe8 so closing this now.

@emyoulation re-reading your comment here. When a person is dropped on an event or visa versa I open the event reference editor which I think is the best way to handle it. That way the role can be selected or if it was an accident it can be aborted. Same for dropping a person on a person to create an association, or a person in a children group for a family to add them, etc.

The painting idea for quickly updating things is a pretty good one.

At the moment some drag and drop is annoying, one thing I need to figure out how to do is pane the window during a drag operation.
