### ISSUE TITLE
Border width and Windoze themes

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#53]
I have discovered that the Layout tab option "Desired border width:" actually DOES work on Windows. (I though it wasn't implemented yet. But maybe it worked on Linux but not Windoze.) But they ONLY work with the Themes add-on active and the with the Raleigh theme active.  

The border setting is ignored with the default theme Adwaita, the HighContrast... and whatever is going on when the Themes add-on is not installed. 

Also, since the field only accepts values from 0 to 5, could the text entry fields be narrower?  It is a long distance between the value & the +/- gadgets.

**Comment by cdhorn** [comment]
Yeah that's implemented and works okay for me on my Fedora machine.

**Comment by emyoulation** [comment]
Definitely behaving badly on Windoze.  But the BIG question is why borders works with the Raleigh theme but none of the others?

**Comment by cdhorn** [comment]
I used the Gtk CSS styling for that, maybe some quirk on Windows with the Gtk port there?

For the config dialog thing I know it's annoying. I'm using the method in Gramps core for that and some things may need tweaking there, not sure. I putzed around with it a little when I first started putting those together and figured look at it another time.

**Comment by cdhorn** [comment]
I see what you meant here. This one too is probably outside my sphere of knowledge but maybe Paul might know. I wonder if this is an issue on MacOS as well.
