### ISSUE TITLE
Show/Hide Private records

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#64]
If you added a Configuration option to "Show Private records (deselected by default), then this would be the only place a user could bring in a person to safely look at a Tree in the interface.

There would need to be Living Person placeholders. On my website I use birth certificate abstractions for living children placeholders.  The capture below is for 4 living offspring; 1 female & 3 males.

![image](https://user-images.githubusercontent.com/69127217/126915746-82ae5c73-5375-497c-8180-73e39aaf2ffa.png)

There is a discussion that will eventually have happen - about Privacy by Default; versus total access by default.  If we do not begin to default to privacy, then sooner or later, a Gramps user will forget to enable privacy and publish a LOT of private information on living persons.  Add they could be financially ruined because of the penalties and liability judgements.

**Comment by cdhorn** [comment]
Closed, see discussion issue #104.
