### ISSUE TITLE
Active Media panel

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#82]
I'm not certain how I got to this page. (Since the pop-ups on Media objects don't have an option to ;Make Active Media' and single-clicking launches the OS helper application to view/edit the media object.  Unlike other where single-clicks that navigate to the object.) It would be nice to be able to navigate to this mode from and Media thumbnail.
![image](https://user-images.githubusercontent.com/69127217/136640237-b6176169-ce77-48c8-b84b-cf4b116afc5d.png)

Regardless, this References list is a very helpful perspective on a Media Object. 

It would be useful to be able to see the ID, Date & Path in the top. (I had to open a Media Object Editor to see this data.)

Also, it would be VERY helpful to have the References show a calculated Age at the Date of the Media object.  With the age marked red if the Date is before Birth or after Death. (Marriage age if a Family is the Reference. Source Publication date if a Citation/Source is the Reference object.) This would provide a quick Sanity Check that you are referencing the correct Object in a Referenced/Tagged Photo.

**Comment by cdhorn** [comment]
@emyoulation 

1. Link image to media page option is in global options now, note if you use the media bar that has a separate option. If you are already on the media page and click on the image it opens in the image viewer instead.

2. Make active media added to menu options in media grouping and for the action bar.

3. The missing items should be there again. 

I'll try to take a look at the age and thumbnail requests soon too.

**Comment by cdhorn** [comment]
Item 4 has been addressed as well now, thumbnails yesterday and age with commit dd04bff69ccdb22d05e6ab43e0a502aead00068b a few minutes ago.

Note the same feature is enabled on the event and citation pages.
