### ISSUE TITLE
Thumbnails instead of full images?

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#83]
On the details for the active photo media object, the top of the panel has the image.  Then the image is repeated for each of the objects referencing it below.

However, if photo tagging was used when setting up the reference, a thumbnail of the rectangular marquee area is shown in other parts of Gramps.

Could this thumbnail be given priority in the Profile view too?

**Comment by cdhorn** [comment]
5408e4db56cb0f94355d53e7552cf918e0c37632 uses thumbnails now when possible
