### ISSUE TITLE
view initialization sequence?

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#88]
Chris,

I don't know what sort of feedback Python gives you when running Gramps in Developer Mode. So this might be a nonviable request.

Are you able to see the sequences of events when switching View Category or View Modes? You might want to review that so you won't take blame for a particular problem that is out of your control.

I have a fairly big database. I have noted that Gramps has cumulative problems switching views... possibly a memory leak, possible a caching problem.

When switching between Categories, the sequence seems to be highlight Navigator bar icon, redraw frames of newly selected category (sidebars), populate sidebars with Gramplets, restore previous cached data of the newly selected category, load tree data, filter data, display data, highlight the active record, update toolbar with contextual icons, update menus with contextual menus, refresh navigation bar to remove highlighting of previous view &  indicate current view. (This is a guess because these activities occur slowly enough that I have time to note each stage being drawn.)

My Gramps often gets stuck after restoring the previously cached data. The toolbar and menus never finish refreshing. (This is a pain because adding a spouse relationship can only be accessed from the menu or toolbar. Your next context menu alleviates this a bit.)

I think that you might want to determine if the core code can be re-sequenced so a View initialization failure is less catastrophic. And so that delays will not shift blame to View mode developers.

****

**Comment by cdhorn** [comment]
My machine is relatively fast so I don't see what you describe regarding slowness. However I did just test a few navigation scenarios and hit a few more bugs, including one where it failed to refresh. I will focus on this over the weekend.

**Comment by cdhorn** [comment]
Brian,

When you have a chance can you check if it still gets "stuck" on you?

I decided the object cache was negligible difference for me so removed it for now at least. That didn't consume much memory though. It caches images as well though and I had that set to 300 not thinking about it so I reduced that down to 32 as I am unsure how much memory that might consume. If you want to experiment with that on your machine look for the `@lru_cache(maxsize=32)` entry in `linked_view.py` and you can scale it up or down.

Regarding slowness, yeah I had not run it on my main tree in some time and had forgotten. I have been using a copy of the example one for development. For people with lots of associated objects it can take a little while, as much as 2.5 seconds on my machine. It's just a lot of data to process and render. I wonder if a different design approach would be faster but it works well enough for me that I have no plans on changing it that radically at this point. Note at the moment if you run from a console you'll see page render times spit out along with navigation history changes, I'll disable that at some point.

Recall this view tracks navigation history across _all_ the objects and tries to keep it in sync with all the list views each of which keeps their own independent history. So when you switch to a list view as soon as you select an object in that view the history is updated in the linked view as well. When you return to the linked view page it needs to redraw as the object changed.

As you navigate the view the navtype of the page follows the primary object. It seemed logical to do that but that may cause problems with Gramplets on that page. I have not been using any or tested any. If you continue to have issues I'd be curious if you remove any Gramplets there if they go away.

**Comment by emyoulation** [comment]
Looking forward to it. Just checked my data plan and it says I'm 3 days from the data throttle reset. Grrr....

-Brian 
 
  On Sat, Nov 20, 2021 at 19:56, Christopher ***@***.***> wrote:   


Brian,

When you have a chance can you check if it still gets "stuck" on you?

I decided the object cache was negligible difference for me so removed it for now at least. That didn't consume much memory though. It caches images as well though and I had that set to 300 not thinking about it so I reduced that down to 32 as I am unsure how much memory that might consume. If you want to experiment with that on your machine look for the @lru_cache(maxsize=32) entry in linked_view.py and you can scale it up or down.

Regarding slowness, yeah I had not run it on my main tree in some time and had forgotten. I have been using a copy of the example one for development. For people with lots of associated objects it can take a little while, as much as 2.5 seconds on my machine. It's just a lot of data to process and render. I wonder if a different design approach would be faster but it works well enough for me that I have no plans on changing it that radically at this point. Note at the moment if you run from a console you'll see page render times spit out along with navigation history changes, I'll disable that at some point.

Recall this view tracks navigation history across all the objects and tries to keep it in sync with all the list views each of which keeps their own independent history. So when you switch to a list view as soon as you select an object in that view the history is updated in the linked view as well. When you return to the linked view page it needs to redraw as the object changed.

As you navigate the view the navtype of the page follows the primary object. It seemed logical to do that but that may cause problems with Gramplets on that page. I have not been using any or tested any. If you continue to have issues I'd be curious if you remove any Gramplets there if they go away.

**Comment by cdhorn** [comment]
A lot of loading time was because of how I calculated relations when I refactored the event frame recently. I really wonder what I was thinking when I did that. Is fixed now and cut my page load times in half.

**Comment by emyoulation** [comment]
That's fantastic! Cutting latency in half is a huge improvement. Congratulations!

**Comment by emyoulation** [comment]
a timing update.  the following starts with a series of Navigations between pages in the example.gramps tree of about 2,400 people.  The last 4 are my main tree of about 46,000.
```

render_page: I0000044 3.1105408668518066
render_page: I0000044 2.9604828357696533
render_page: I0000044 3.8100006580352783
render_page: I0000044 3.2307381629943848
render_page: I0001113 1.3980004787445068
render_page: I0001113 1.2729997634887695
render_page: I0001117 1.6199982166290283
render_page: E0000200 0.33299827575683594
render_page: I0001117 1.3359994888305664
render_page: I0001117 1.7355568408966064
render_page: I0001114 1.2579998970031738
render_page: I0001114 1.1734538078308105
render_page: I0001114 0.36100029945373535
render_page: I0000044 2.979004144668579
render_page: I0000044 2.9589626789093018
2021-12-10 19:00:01.946: WARNING: dummydb.py: line 787: database is closed
2021-12-10 19:00:01.947: WARNING: dummydb.py: line 788: handle  does not exist in the dummy database
2021-12-10 19:00:03.666: WARNING: dummydb.py: line 834: database is closed
2021-12-10 19:00:03.667: WARNING: dummydb.py: line 835: handle d24aa5b66d94b7306c401e73ab6 does not exist in the dummy database
render_page: HJS-4203-4 15.134439945220947
render_page: HJS-4203-4 7.6919519901275635
render_page: HJS-4203-2 46.72953748703003
render_page: HJS-4203-2 46.473997354507446
```

**Comment by cdhorn** [comment]
Ugly. Yeah, Lewis takes about .3 seconds on my machine and I see he averages 3 or more on yours.

My main tree is about 20,000 people and is relatively fine, longest person render takes 3 seconds or so.

I should capture some other metrics there.

What processor model/speed, how much memory, and do you still use spinning disk?

**Comment by emyoulation** [comment]
That big slowdown seemed to be after spawning an Association window with 20 associations related to DNA snipits

I'm using a HP Pavilion g7 notebook with AMD A6-3420M quad core 8GB & spinner HDD. 64bit Win10 Home

**Comment by cdhorn** [comment]
Ah, of course, the relationship calculator.  I should make that optional in the person ref frame. 

I forget, I think I'm using Gramps default almost but not quite everywhere for that as well. I wonder if I should let you tailor that differently in the view.

**Comment by emyoulation** [comment]
I'm wondering if your experiments building the the LinkedView gives you enough insight to the Gramps core code design (and how it calls Gtk to populate the GUI) to look through the sequence when Gramps switches view modes or categories?

Like the [Config screen responsiveness you fixed with the 5 second delay](https://github.com/cdhorn/LinkedView/issues/99#issue-1073315255), the GUI elements (refresh of toolbar, navigator bar and context menus) seems to happen only after the main window finishes populating. However, the status bar continues to quickly update the Active Object listed even when the rest of the GUI becomes unresponsive.

Since there is a bug somewhere that causes massive lag to suddenly affect populating the Relationship view, the toolbar & menus can become unavailable. (It might also be related to the Sidebar/Bottombar content refreshing. Serge added 2 variants of 'freezes' to the Gramplets shells. They help when CPU intensive Gramplets are active. It remains unclear if Gramplets in the non-active tabs continue to refresh or only to topmost & spawned gramplets.)

This [core bug 12276](https://gramps-project.org/bugs/view.php?id=12276) will affect the ability to access your new view mode. 

If you see an obvious order of operation flaw or an opportunity where deferring populating the main view could help, perhaps you could add a note to the MantisBT bug report?

**Comment by emyoulation** [comment]
Just so you don't dig for a flaw in your view that does not exist...

This problem appears to be in the View category & mode change management in  in Gramps. It might exist in all categories but is most visible in the Relationships category. 

(Possibly because only the Relationships category has to populate from all tables. Charts & Geography categories views have to open more tables too. I've occasionally seen them affected to a lesser degree.)

**Comment by cdhorn** [comment]
Note I did finally find my oversight / bug yesterday that was causing a second page redraw to issue. That may have exacerbated an existing problem if making use of this view.

**Comment by cdhorn** [comment]
Closing this one as think this is working okay now and have later similar one.
