### ISSUE TITLE
leftover ini

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#89]
Downloaded the 0.99 version zip, deleted the old Profile View folder, unzipped to a LinkedView-master, renamed the Folder as "LinkedView" and opened Gramps.  An error dialog appears saying the Registration file is probably bad and directing user to error messages in the Command Line Interface.  
![image](https://user-images.githubusercontent.com/69127217/143724490-30d5c1e5-4b70-4358-b1b8-c37202744ad7.png)

The following CLI error message appears:

2021-11-27 18:08:25.952: WARNING: _manager.py: line 308: Plugin error (from 'profileview'): cannot import name 'get_config_option'

A different subject:
Please consider decreasing the version to 0.50 (or even lower!) before releasing first version via the Plugin Manager installer.  A 0.50 will give yourself space for 49 of the 0.01 increment revisions to shake out problems before calling it a 1.0 version. Right now there is only room for one rev. to be recognized as an update.  (expect that alpha testers should be competent enough to manually clean out the experimental versions.) 

You know how frequently you have posted revisions to this source since beginning the experimental project. If you do only 5 tweaks a day, rev'ing in 0.01 increments has room for 10 days of beta cycle. Is that enough?

**Comment by cdhorn** [comment]
The error message states the view name is `Profile` which indicates you're trying to load an older version of the plugin still.  The new view name is `Linked`

Did you perhaps rename a previous copy which is still laying around in the plugins directory?  If so Gramps will see the `.gpr` file for it and will try to load it.

**Comment by cdhorn** [comment]
Suggestion on lowering revision noted, I haven't been paying attention to that.

**Comment by cdhorn** [comment]
I'm assuming this is resolved so closing it now.
