### ISSUE TITLE
LinkedView toolbar Help button?

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#90]
Please look into adding a Help button to the toolbar when the LinkedView relationships category view mode is active. There is no doubt that this view mode will require extensive help documentation. (Probably multiple web pages: for the main view mode & perhaps a separate URLs for each configuration section. The amount of content to be covered is daunting!) The wiki teams needs to begin outlining the Help soon. 

A good target url would be:
https://www.gramps-project.org/wiki/index.php/Addon:LinkedView

Please consider the probability that the .gpr.py parser is likely to be expanded to allow a (translation ready) help_url [register option](https://www.gramps-project.org/wiki/index.php?title=Gramplets#Register_Options) to be used with other plugin types than "Gramplets". (That option current causes the parser to have an unhandled failure with other plugin types.)  So can the design be ready for the main URL to be passed from that .gpr.py file?

Currently, the only view modes that have a help button are the 2 [Life Line](https://www.gramps-project.org/wiki/index.php/Life_Line_Chart_View) view mode addons for the Charts category view. 

The Life Lines 'help' GUI implementation is not ideal. The button is inside the main window of the view when it should be in the Toolbar. (Ideally, placement would be immediately adjacent to the Configure toolbar button: Configure button opens Preferences for the active view mode, Help button reveals the wiki for the active view mode.)

Also, the Life Lines 'help' iconography is not in the 'Tango' style. It is a strange black&white stack of black call-out bubbles with a question mark. (One of the non-obvious oddities is that the call-out bubble points to the upper-right ... towards the right Gramplet sidebar. Since the content being described with the help is the main view area, intuitively the call-out should point to the lower left.)   The [Tango](https://wikipedia.org/wiki/Tango_Desktop_Project) icon for help is either a [red & white life preserver ring](https://commons.wikimedia.org/wiki/File:Help-content.svg) or a [round blue button with a white question mark](https://openclipart.org/detail/35203/tango-help-browser).

If you are successful making Help available for a view mode, it may be wise to keep the pieces of the implementation containerized. First, so the code might be re-used as a template by other View Mode developers. And second, against the probability that the core Gramps modules will add this functionality (linked from the .gpr.py registration file help_url) in the future.

**Comment by cdhorn** [comment]
Help button added using suggested link in d465760f62cd246220da0144d5decb6302c9f43b

I did not investigate, if the help_url thing is made available in the registration can revisit and update code to use that then.
