### ISSUE TITLE
Disorientation during use

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#92]
I'm finding the changing of category disorienting.  The variation where there is a context bar with secondary objects above the focal object bar causes momentary disorientation during Navigation of the focus.

Could you try and experiment?  On the right side where the ID (and occasional Bookmark icon) for the focal object is shown, could you display a Large SVG (in avatar or thumbnail size, not toolbar icon size) of the category of the focal object? (Are the tiny icons for secondary objects using the 16x16/22x22 PNGs or the SVGs set to a specific size? If it is the second, then the it may be easie to expand the intuitive metaphor of Primary being large, secondary being small.)

By the way, once I puzzled out what that tiny bookmark icon was, I really that feedback. Maybe you could also have a Home button icon when the focal person is the Home Person.

If the large tango icon avatar looks too cartoonish or makes the view look like an elementary school worksheet, maybe having the icon 80% transparent would make look like a water mark instead?

**Comment by cdhorn** [comment]
Let me think about the navigation concern and knowing which is the focal object a bit.

Just added support for home/default person indicator as suggested. I should have thought of that, fits right in the model. The idea obviously is to convey as much information visually at a glance as possible. 

I'm using the button size so it scales the icons to 16x16. I'm not sure which it prefers over which but I think if you provide them pre-scaled it saves a little processing overhead.

**Comment by cdhorn** [comment]
When you can check out commit 13ab1aef783d0a346da264724646608df2bb2d91 which is version .56

Under global options there is a highlight focal object option disabled by default at the moment and I also made the color selectable. Let me know if you find that approach to help, I think it is a better option than adjusting icon sizes.

**Comment by cdhorn** [comment]
And 0cb14cf761fb9887d87c1fc9288be0f7bb3f0adf adds option under Active Family to disable display of parents for the couple.

**Comment by cdhorn** [comment]
And 7bfa116e0294d61aad1d3e8b1e680a44c430fe8a which is .57 adds option to select default frame background color to use when no calculated coloring is applied.

**Comment by emyoulation** [comment]
That should be an interesting approach. I look forward to trying it.

I was thinking of the future  -- when you weren't trying to nail down a release and were adding functionalities. An avatar would make a good hint that an anchor for context menu was at that spot.

There are various actions in the context pop-up menus for the active record in different Categories. The LinkedView seems like a good place to navigate access to those actions without using the Category Navigator bar, then having to find the object you were just looking at  in the Relationships view. (Since the active record focus isn't synchronized in the Families, Note, Citation, Source, Media categories like the Active Person focus.) I have taken to clipboarding objects from the ORIGINAL Relationships view mode so that I have access to navigate focus in the other categories via its Make Object Active context menu option or the make a Filter option. Unfortunately, clipboarding from that view adds those special "ref" objects in some cases. The "ref" objects carry extra context (like Child/Parent relationship for People or Roles for Events) but they don't have any context menu.

Some of the Context menus options:

(Standby for screen captures. Have to switch devices to capture & edit posting to insert)

For a selected Person object in the People View:

For a selected Person Object in the Clipboard:

For the original Relationship view mode:

**Comment by emyoulation** [comment]
OK... The marriage screen is just too disorienting. The side-by-side vertically arranged parents marriages **over** the horizontally AND vertically oriented spouse family **over** vertically arranged offspring is just too many directions interwoven with too many mismatched seams.

The focus highlight color helped a little. (Although my change of the Green color to yellow was not applied immediately and I cannot see anywhere that the background color is applied. Weird)

The children are NOT so disorienting because of the collapsible section label.

Maybe a collapsible section for "Parents and In-laws" would help? I recall you wrote that the this section can be disabled in Configuration but I cannot find that option.

**Comment by cdhorn** [comment]
Active tab, Family, Show parents of couple. 

Making it collapsable is an interesting thought.

**Comment by emyoulation** [comment]
If you make it collapsible, how about changing the Configuration option? Make the choice whether the section is collapsed by default (rather than entirely disabled). There'd be Minimal screen usage when collapsed and less need for documentation... and FAR less "wait... I saw parents of both spouses somewhere but where?" angst.

Additionally, the same Collapsible interfacing could be added for the other Objects that have additional context inserted above. (Like Citations that have a Source superior context section. Trying out different descriptive phrases for elements of your GUI metaphor. Trying to discover which leave a bad aftertaste.) Thus making the metaphor more consistent.

An eventual windowing option for the Configuration would be to add a context menu for collapsible menus. Such a menu has 3 obvious & distinctly opposing approaches. 
1) the context menu has a parallel option for configuring: default collapse state, or any other configure option. It is synchronized with the Configuration GUI
2) the context menu replaces the GUI access to the configuration for that feature
3) the context menu is a hotlink to the Configuration screen with that option

The benefits/drawbacks of each approach are arguable.  

The first brings the configuration more intuitively close to the feature. But it doesn't sacrifice the comprehensive overview of all possible configuration options and their relax to similar features.

The second has the intuitive value of the first  but reduces the overwhelming impact of the comprehensive compendium of options.

The third conveys the user to an overview of similar configuration options so that they are reminded to make harmonious interface selections.

**Comment by cdhorn** [comment]
When you have a chance please check latest commit.  I have enhanced the family frame so there is now a compact view which you will likely find a better fit, at least I do. 

I updated the default options to use the compact view in the groups, and when on the family page view to use the regular for the active couple but to use the compact for the parents. I think that is a better setup. New options to manage it under the Family object under the Active and Group config tabs.

**Comment by emyoulation** [comment]
I'm not thinking clearly Tonite. Making it an early night and will give it a try in the morning.

Thanks for all the work you are doing here & being so open to feedback.

**Comment by emyoulation** [comment]
I like the compact view for the Parents of the Family Spouses.

But maybe, in addition to the duration of that marriage, it also displays the birth order and count of children, plus the marriage length at birth?

I cannot say that I like the Media defaulting on the left.  It gives it an unnatural superiority to the Focus object. And since the configuration is scrolled off the bottom of the Global tab, I spent too much time searching for it.  Putting that panel to the right by default might be better.

**Comment by cdhorn** [comment]
> But maybe, in addition to the duration of that marriage, it also displays the birth order and count of children, plus the marriage length at birth?

I am unsure I am following you. Here you are referring just to the parent family frames?

I could provide an ordered, comma delimited list of children as an option I guess. I don't think numbering them or putting the length of marriage when they were born in the frame makes sense though and would add a ton of clutter.

But I do like the length of marriage idea. I can include the marriage duration at time of birth in the child frames on that page, or better yet the age of the mother at time of birth.  Or perhaps both.  I will look at that.

`I cannot say that I like the Media defaulting on the left.`

Ah, here I prefer it that way, so that is not likely to change and is why it is a config option! 😀

**Comment by cdhorn** [comment]
Okay I see what you are saying. Yes, I can do that, issue #101 will enable it.

**Comment by cdhorn** [comment]
Closing this, think it's sort of addressed in my mind with the highlighting and compact family frame, and added the custom field for the child info in #101
