### ISSUE TITLE
spawned windows are not ID'd for the Gramps Windows menu

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#94]
Spawning a secondary object window by clicking a its icon causes the "Windows" tab to be shown (if it was not already shown) to Gramps menu.

The spawned window is not correctly added to this menu.

Each spawned 2ndry window adds another "Undefined submenu" with a sublisting of "Undefined menu..." (the wiki would list this as "Windows -> Undefined submenu -> Undefined menu...") Note that there are multiples of identical menu items with multiple spawned 2ndry object windows.

Other odd behavior:

* each spawned window creates a blank white rectangle in the center of the screen, then populates it and resizes it.  This means that nearly windows has to be dragged upwards to show the resized window. 
* the 2ndry object windows are spawned with catholic abandon.  Could there be a Chinese "one child policy" population control option? With that option, only 1 window can be spawned. That single existing window would re-purposed for each successive 2ndry object. 
* the unexpected error when spawning these windows is intertwined with the GIMP failure. (Probably a Gtk interaction) The spawning works fine initially.  But after GIMP fails to launch, LinkedView fails to spawn.  The GIMP error dialog cannot interfere with the Windows screenshot applications: "Sample-colorize.exe - Entry Point Not Found : The procedure entry point libintl_printff could not be located in the dynamic link library C:\Programs Files\GIMP 2\lib\gimp\2.0\plug-ins\sample-colorize.exe" Successive similar dialog appear for every plug-in GIMP tries to load.  Eventually, a GIMP message appear that the .jpg extension is not recognized. After that, attempts to spawn 2ndry object windows give this error:
```
* 7256118: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView\view\frames\frame_widgets.py", line 480, in __indicator_click
    self.grstate.show_group(self.obj, group_type)
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView\view\common\common_classes.py", line 418, in show_group
    return self.callbacks["show-group"](obj, group_type)
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView\linked_view.py", line 840, in show_group
    self.grstate, obj, group_type, key, self._clear_window
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView\view\groups\group_widgets.py", line 70, in __init__
    self.group_box.pack_start(group, expand=False, fill=True, padding=0)
TypeError: Argument 1 does not allow None as a value
```

**Comment by cdhorn** [comment]
See Global options, top right, maximum number of object group windows. You can set it to 1.

I should add an option to make it a modal and not a separate window probably. 

I agree this whole feature has issues and needs a bit more work, you are seeing the results of the initial iteration and I'm likely not managing them correctly.

**Comment by cdhorn** [comment]
Latest commit greatly improves the window titles for nested objects and adds the method needed to generate the Windows menu label. Note while you can spawn nested ones I treat them the same. I also switched to using the ManagedWindow class method for saving size and position, that is now done based on group and saved in the core gramps.ini but in an isolated namespace.

If you did not notice, once the window is open it is "static" and you can navigate elsewhere and reference it. If you update or modify data at some point then if the window group is a child of a secondary object it does not have enough context to rebuild itself so it closes, but otherwise the group will refresh itself.

I should have set it up so you could spin the whole page off, or have an option to spin the page focal off as part of the window. I will likely add such features. Drag and drop of course works across it all.

**Comment by emyoulation** [comment]
In being static, these spawned windows are closely related to quickviews. I will have to experiment a bit further to understand which aspect of drag'n'drop works. 

In the distant future, these secondary object spawned window implementations might be good candidates to disentangle from your View mode. 

By converting them into separate QuickViews and converting the 2ndry icon GUI mechanism into a configurable QuickView caller, you'd gain power & flexibility without some of the maintenance drawbacks. (So each of the secondary icons could have a Configuration of which QuickView of its Category was called... or maybe even causes the QuickView Gramplet in LinkedView sidebar/bottombar to refocus it's configuration.) This would like you leave your implementation static. The QuickView Gramplet would inherit the headache of making them dynamic. Plus, you gift every other view category your LinkedView vision of interrelationships between primary & secondary objects as new QuickViews.

Perhaps this was what you meant by "spin off"?

**Comment by cdhorn** [comment]
I'm not sure I explained myself well, something I have trouble with at times. Yes, you can think of them as being like the quick view windows except not disentangled so you can trigger navigation events in the main view from them and they are still enabled for drop operations.

By spin off I mean render the full page view in a separate window, not just a group, so if you had dual monitors you could spin or peel off a copy of the main view and then navigate to someone else and compare them.

**Comment by emyoulation** [comment]
Wow! That spin-off sounds frighteningly powerful. Almost nuclear, in fact. I expect this would be best done with a LinkedView Gamplet for the LinkedView view mode. Where drag'n'drop between view mode & Gramplet (with objects of the same type) would invoke a Merge dialog rather than an insert or overwrite. And with the option for synchronized navigation. So... if you lined up an imported a 3-generation GEDCOM twig on the equivalent focal person,  you could merge/compare the navigate to the father (or n<sup>th</sup> child) in either window & have the synchronized window do the same!

Everybody would wet their panties over something like that!

**Comment by cdhorn** [comment]
Added page copy support in the last handful of commits.

The number of open page windows is tracked separately from open group windows with a separate global config parameter.

The edit-copy icon is being used to peel a page off, it's next to the help icon.

Lightly tested so far. Some further work needed to handle refreshes when viewing pages for secondary objects and the secondary object changed. 

Enjoy!

**Comment by cdhorn** [comment]
Closing this now post 30135ec05fa144f6c8321793017f69ac7bea07f8

**Comment by emyoulation** [comment]
Retested with Version: 0.90

The only remaining issue discovered is that the Minimize window gadget continues to simultaneously affect all windows of the APPLICATION not the individual window. (Only the Console window of the Gramps instance is not affected.)
