### ISSUE TITLE
Reset config to Default error

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#96]
revision 0.58 on Windows 10

I had a Blank Tree that I added a hierarchy of 4 Places.  Went to Relationships and tried to discover if there was a way to get to the in focus Place. (There wasn't) 
So I changed Trees to the Example.gramps tree but the LinkedView was still empty. 

Tried changing Persons and coming back in.  Still blank. Hit the Home Person button.  Still blank.  Thought maybe the Preferences were somehow fouled up.  So decided to reset to defaults.

In Configuration
Defaults button
<kbd>**select the "Reset all options to defaults, not just this page."**</kbd>
Press OK. 

Error 

8350794: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView\view\common\common_utils.py", line 680, in reset_option_space
    default_value = self.config.get_default(option)
  File "C:\Program Files\GrampsAIO64-5.1.4\gramps\gen\utils\configmanager.py", line 429, in get_default
    (section, setting))
AttributeError: No such config setting name: 'options.colors.roles.border-other'

**Comment by cdhorn** [comment]
Closing this now too.
